#Postgresql config
spring.datasource.url= jdbc:postgresql://dpg-d7eu95e7r5hc73c7vlmg-a.singapore-postgres.render.com/moneymantra_014q
spring.datasource.username= moneymantra_014q_user
spring.datasource.password= SR18HY961wZlScrKb3jXMgZ6Yjv15KR6