#Postgresql config
spring.datasource.url=jdbc:postgresql://dpg-dad5ou710e5c73derg4g-a.singapore-postgres.render.com:5432/moneymantra_ashnav
spring.datasource.username=moneymantra_ashnav_user
spring.datasource.password=${DB_PASSWORD}