#Postgresql config
spring.datasource.url= jdbc:postgresql://dpg-d9p2v2142hec73ctbja0-a.singapore-postgres.render.com/moneymantra_5p13
spring.datasource.username= moneymantra_5p13_user
spring.datasource.password= RZ5J62e7IzLVVb2mXLjOxXvrNTeqI3D5