#Postgresql config
spring.datasource.url= jdbc:postgresql://dpg-d6s2bu9aae7s73d2sra0-a.singapore-postgres.render.com/moneymantra
spring.datasource.username= moneymantra_user
spring.datasource.password= v3rE76iroAZLnmbmNu7kQATxOdBjr203